### ISSUE TITLE
Wrap config values in quotes

### ISSUE THREAD

**Issue by thoma127** [umn-asr/sessions_data_service#76]
If a value in the .env.production.erb file contains a "#" character it is not wrapped in quotes, the value will get truncated. Make sure all variables in .env.production.erb are wrapped in quotes.

**Comment by thoma127** [comment]
That's my understanding.

**Comment by thoma127** [comment]
I also think this is a fairly rare occurrence. But it has severe consequences when it does happen.

**Comment by eeklund** [comment]
Given the unexpected behavior could exhibit itself months or even years later with a simple password rotation, and given that the fix is literally auditing .env files and wrapping values with quotes, this is one to do. It will potentially prevent a production application from being locked after a change in the future when the behavior is not expected.

As an alternative workaround (albeit not as robust a solution) we could just remove the `#` from our password generation tooling. This comes with remember that character is a no-no. I'm not fond of this solution, but it would reduce the likelihood of a later occurrence.

**Comment by dlagerro** [comment]
FWIW - our password generating tooling [currently uses `alphanumeric` random strings](https://github.com/umn-asr/oracle_operations/blob/1e6706720b1beee0d2b49974f1abda56d797620a/lib/password.rb#L8). Sometimes we get passwords from other places - e.g. from OIT for OIT managed resources - and we don't have control over what rules they use.

I am torn on voting. It should get done, so it's at least 👍 but does it need to get done right away?
